apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: controller
  name: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - image: igorira/micro-livraria-controller
        imagePullPolicy: "Always"
        name: controller
        ports:
        - containerPort: 3000
        env:
        - name: INVENTORY_HOST
          value: http://10.0.43.223:3002
        - name: SHIPPING_HOST
          value: http://10.0.125.87:3001
