name: "Kubernetes controller"

on: [push]

# Environment variables available to all jobs and steps in this workflow
env:
  REGISTRY_NAME: igorira
  CLUSTER_NAME: aks-eesdevops
  CLUSTER_RESOURCE_GROUP: rg-eesdevops-dev-main
  NAMESPACE: eesdevops-namespace
  SECRET: micro-livraria-cr
  APP_NAME_CONTROLLER: micro-livraria-controller
  APP_NAME_FRONTEND: micro-livraria-frontend
  APP_NAME_INVENTORY: micro-livraria-inventory
  APP_NAME_SHIPPING: micro-livraria-shipping
  BUILD_FILE_CONTROLLER: ./services/controller
  BUILD_FILE_FRONTEND: ./services/frontend
  BUILD_FILE_INVENTORY: ./services/inventory
  BUILD_FILE_SHIPPING: ./services/shipping
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    
    # Connect to Docker
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push controller
      id: docker_build_controller
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.BUILD_FILE_CONTROLLER }}
        push: true
        tags: ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME_CONTROLLER }}:${{ github.sha }}

    - name: Build and push frontend
      id: docker_build_frontend
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.BUILD_FILE_FRONTEND }}
        push: true
        tags: ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME_FRONTEND }}:${{ github.sha }}

    - name: Build and push inventory
      id: docker_build_inventory
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.BUILD_FILE_INVENTORY }}
        push: true
        tags: ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME_INVENTORY }}:${{ github.sha }}

    - name: Build and push shipping
      id: docker_build_shipping
      uses: docker/build-push-action@v2
      with:
        context: ${{ env.BUILD_FILE_SHIPPING }}
        push: true
        tags: ${{ env.REGISTRY_NAME }}/${{ env.APP_NAME_SHIPPING }}:${{ github.sha }}
    
    # Set the target Azure Kubernetes Service (AKS) cluster. 
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
    
    # Create namespace if doesn't exist
    - run: |
        kubectl create namespace ${{ env.NAMESPACE }} --dry-run -o json | kubectl apply -f -
    
    # Create image pull secret for ACR
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: index.docker.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: ${{ env.SECRET }}
        namespace: ${{ env.NAMESPACE }}
        force: true
    
    # Deploy app to AKS
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
            k8s
        images: |
            ${{ env.REGISTRY_NAME }}.docker.io/${{ env.APP_NAME_CONTROLLER }}:${{ github.sha }}
            ${{ env.REGISTRY_NAME }}.docker.io/${{ env.APP_NAME_FRONTEND }}:${{ github.sha }}
            ${{ env.REGISTRY_NAME }}.docker.io/${{ env.APP_NAME_INVENTORY }}:${{ github.sha }}
            ${{ env.REGISTRY_NAME }}.docker.io/${{ env.APP_NAME_SHIPPING }}:${{ github.sha }}
        imagepullsecrets: |
            ${{ env.SECRET }}
        namespace: ${{ env.NAMESPACE }}
